// <auto-generated />
using System;
using CIVS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIVS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328010443_AddFacturaNavegacion")]
    partial class AddFacturaNavegacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIVS.Models.Auditoria", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaId"));

                    b.Property<string>("AuditoriaAccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AuditoriaDescripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AuditoriaEntidad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("AuditoriaEntidadId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("AuditoriaEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AuditoriaFecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("AuditoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("CIVS.Models.Cita", b =>
                {
                    b.Property<int>("CitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitaId"));

                    b.Property<DateTime>("CitaFechaCreada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CitaFechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CitaFechafin")
                        .HasColumnType("datetime2");

                    b.Property<string>("CitaMotivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstadoCita")
                        .HasColumnType("int");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("CitaId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("CIVS.Models.Consulta", b =>
                {
                    b.Property<int>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultaId"));

                    b.Property<int>("CitaId")
                        .HasColumnType("int");

                    b.Property<bool>("ConsultaEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ConsultaFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConsultaNotasClinicas")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ConsultaPlanTratamiento")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ConsultaSignosVitales")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ConsultaId");

                    b.HasIndex("CitaId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("CIVS.Models.ConsultaDiagnostico", b =>
                {
                    b.Property<int>("ConsultaDiagnosticoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultaDiagnosticoId"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<int>("DiagnosticoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.HasKey("ConsultaDiagnosticoId");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("DiagnosticoId");

                    b.ToTable("ConsultaDiagnosticos");
                });

            modelBuilder.Entity("CIVS.Models.Diagnostico", b =>
                {
                    b.Property<int>("DiagnosticoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosticoId"));

                    b.Property<string>("DiagnosticoCodigo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("DiagnosticoEstado")
                        .HasColumnType("bit");

                    b.Property<string>("DiagnosticoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DiagnosticoId");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("CIVS.Models.Especialidad", b =>
                {
                    b.Property<int>("EspecialidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadId"));

                    b.Property<bool>("EspecialidadEstado")
                        .HasColumnType("bit");

                    b.Property<string>("EspecialidadNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("EspecialidadId");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("CIVS.Models.Examen", b =>
                {
                    b.Property<int>("ExamenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamenId"));

                    b.Property<string>("ExamenDescripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ExamenEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExamenFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamenNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ExamenPrecio")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("ExamenId");

                    b.ToTable("Examenes");
                });

            modelBuilder.Entity("CIVS.Models.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<int?>("CitaId")
                        .HasColumnType("int");

                    b.Property<decimal>("FacturaDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FacturaEstado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FacturaFecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FacturaFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FacturaImpuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FacturaNumero")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("FacturaSubtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FacturaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("CitaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("CIVS.Models.FacturaDetalle", b =>
                {
                    b.Property<int>("FacturaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaDetalleId"));

                    b.Property<int>("DetalleCantidad")
                        .HasColumnType("int");

                    b.Property<string>("DetalleDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("DetalleDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DetallePrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DetalleTotalLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ExamenId")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicamentoId")
                        .HasColumnType("int");

                    b.HasKey("FacturaDetalleId");

                    b.HasIndex("ExamenId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("FacturaDetalle");
                });

            modelBuilder.Entity("CIVS.Models.HorarioMedico", b =>
                {
                    b.Property<int>("HorarioMedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorarioMedicoId"));

                    b.Property<DateTime>("HorarioFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("HorarioNota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("MedicoHorarioDisponible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MedicoHorarioFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MedicoHorarioInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.HasKey("HorarioMedicoId");

                    b.HasIndex("MedicoId");

                    b.ToTable("HorarioMedicos");
                });

            modelBuilder.Entity("CIVS.Models.Inventario", b =>
                {
                    b.Property<int>("InventarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventarioId"));

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InventarioEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InventarioFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("InventarioId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("CIVS.Models.InventarioMovimiento", b =>
                {
                    b.Property<int>("InventarioMovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventarioMovimientoId"));

                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<int>("MovimientoCantidad")
                        .HasColumnType("int");

                    b.Property<bool>("MovimientoEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MovimientoFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovimientoMotivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MovimientoTipo")
                        .HasColumnType("int");

                    b.HasKey("InventarioMovimientoId");

                    b.HasIndex("InventarioId");

                    b.ToTable("InventarioMovimientos");
                });

            modelBuilder.Entity("CIVS.Models.Medicamento", b =>
                {
                    b.Property<int>("MedicamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicamentoId"));

                    b.Property<string>("MedicamentoConcentracion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("MedicamentoEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MedicamentoFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicamentoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("MedicamentoPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MedicamentoPresentacion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("MedicamentoUnidad")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("MedicamentoId");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("CIVS.Models.Medico", b =>
                {
                    b.Property<int>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicoId"));

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<string>("MedicoApellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicoColegiado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicoEmail")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("MedicoEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MedicoFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicoNombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicoTelefono")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.HasKey("MedicoId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("CIVS.Models.MetodoPago", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoPagoId"));

                    b.Property<string>("MetodoPagoDescripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("MetodoPagoEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MetodoPagoFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPagoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MetodoPagoId");

                    b.ToTable("MetodoPagos");
                });

            modelBuilder.Entity("CIVS.Models.OrdenExamen", b =>
                {
                    b.Property<int>("OrdenExamenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenExamenId"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<int>("ExamenId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenEstado")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrdenFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultadoArchivoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ResultadoFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultadoTexto")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("OrdenExamenId");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("ExamenId");

                    b.ToTable("OrdenExamenes");
                });

            modelBuilder.Entity("CIVS.Models.OrdenExamenDetalle", b =>
                {
                    b.Property<int>("OrdenExamenDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenExamenDetalleId"));

                    b.Property<bool?>("FueraDeRango")
                        .HasColumnType("bit");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("OrdenExamenId")
                        .HasColumnType("int");

                    b.Property<string>("ParametroNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RangoReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResultadoUnidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResultadoValor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrdenExamenDetalleId");

                    b.HasIndex("OrdenExamenId");

                    b.ToTable("OrdenExamenDetalles");
                });

            modelBuilder.Entity("CIVS.Models.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PacienteId"));

                    b.Property<string>("PacienteApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PacienteCorreo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PacienteDPI")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("PacienteDireccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("PacienteEstado")
                        .HasColumnType("bit");

                    b.Property<string>("PacienteEstadoCivil")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("PacienteFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PacienteNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("PacienteNombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PacienteTelefono")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.HasKey("PacienteId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("CIVS.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<bool>("PagoEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PagoFecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PagoMonto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PagoReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PagoId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("MetodoPagoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("CIVS.Models.Receta", b =>
                {
                    b.Property<int>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecetaId"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<bool>("RecetaEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RecetaFechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecetaObservaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("RecetaId");

                    b.HasIndex("ConsultaId");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("CIVS.Models.RecetaDetalle", b =>
                {
                    b.Property<int>("RecetaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecetaDetalleId"));

                    b.Property<string>("Dosis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Duracion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Frecuencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Indicaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("int");

                    b.Property<int>("RecetaId")
                        .HasColumnType("int");

                    b.HasKey("RecetaDetalleId");

                    b.HasIndex("MedicamentoId");

                    b.HasIndex("RecetaId");

                    b.ToTable("RecetaDetalles");
                });

            modelBuilder.Entity("CIVS.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolDescripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("RolEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RolFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CIVS.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("UsuarioApellidos")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("UsuarioEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UsuarioFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioNombres")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("UsuarioPasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UsuarioUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CIVS.Models.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioRolId"));

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("UsuarioRolEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UsuarioRolFechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioRolId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("CIVS.Models.Auditoria", b =>
                {
                    b.HasOne("CIVS.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CIVS.Models.Cita", b =>
                {
                    b.HasOne("CIVS.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIVS.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("CIVS.Models.Consulta", b =>
                {
                    b.HasOne("CIVS.Models.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("CIVS.Models.ConsultaDiagnostico", b =>
                {
                    b.HasOne("CIVS.Models.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIVS.Models.Diagnostico", "Diagnostico")
                        .WithMany()
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Diagnostico");
                });

            modelBuilder.Entity("CIVS.Models.Factura", b =>
                {
                    b.HasOne("CIVS.Models.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("CitaId");

                    b.HasOne("CIVS.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("CIVS.Models.FacturaDetalle", b =>
                {
                    b.HasOne("CIVS.Models.Examen", "Examen")
                        .WithMany()
                        .HasForeignKey("ExamenId");

                    b.HasOne("CIVS.Models.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIVS.Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId");

                    b.Navigation("Examen");

                    b.Navigation("Factura");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("CIVS.Models.HorarioMedico", b =>
                {
                    b.HasOne("CIVS.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CIVS.Models.Inventario", b =>
                {
                    b.HasOne("CIVS.Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("CIVS.Models.InventarioMovimiento", b =>
                {
                    b.HasOne("CIVS.Models.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("CIVS.Models.Medico", b =>
                {
                    b.HasOne("CIVS.Models.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("CIVS.Models.OrdenExamen", b =>
                {
                    b.HasOne("CIVS.Models.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIVS.Models.Examen", "Examen")
                        .WithMany()
                        .HasForeignKey("ExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Examen");
                });

            modelBuilder.Entity("CIVS.Models.OrdenExamenDetalle", b =>
                {
                    b.HasOne("CIVS.Models.OrdenExamen", "OrdenExamen")
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("OrdenExamenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenExamen");
                });

            modelBuilder.Entity("CIVS.Models.Pago", b =>
                {
                    b.HasOne("CIVS.Models.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIVS.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("CIVS.Models.Receta", b =>
                {
                    b.HasOne("CIVS.Models.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("CIVS.Models.RecetaDetalle", b =>
                {
                    b.HasOne("CIVS.Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIVS.Models.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("CIVS.Models.UsuarioRol", b =>
                {
                    b.HasOne("CIVS.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIVS.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CIVS.Models.Factura", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("CIVS.Models.OrdenExamen", b =>
                {
                    b.Navigation("OrdenDetalles");
                });

            modelBuilder.Entity("CIVS.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("CIVS.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
